### ISSUE TITLE
now love.exe is ignoring args - it is impossible to run debug at IDEA / ZeroBrane Studio

### ISSUE THREAD

**Issue by D0NM** [megagrump/polyamory#1]
![image](https://user-images.githubusercontent.com/11454242/47593734-dad9eb00-d991-11e8-986e-b4f485326968.png)

Love.exe is ignoring args - it is impossible to run debug at IDEA / ZeroBrane Studio

The pic is self explainable. 
Good work!

**Comment by D0NM** [comment]
)))) of course it does. Since very beginning.

https://love2d.org/forums/viewtopic.php?t=3185 

love test.love  -e  -d

**Comment by megagrump** [comment]
Sure, it allows access to command line args, [polyamory is using that](https://github.com/megagrump/polyamory/blob/7b8058de044c0cd68967e0bf59084b3c6b51b368/src/main.lua#L14) to do its job.

What I meant was, is there any documentation what `-e` and `-d` options mean and in what places on the command line they can occur? If I want to fully support it, I need some info about it.

**Comment by megagrump** [comment]
No, I don't. I will add code to pass them through.
